name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the action on push to the main branch

# Add write permissions to allow the action to push to the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm' # Enable caching for npm

      - name: Install Dependencies
        run: npm ci # Use ci for faster, more reliable installs

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
